### ISSUE TITLE
hydrate function getVpcEipARN failed with panic runtime error

### ISSUE THREAD

**Issue by ben417** [turbot/steampipe-plugin-aws#1307]
**Describe the bug**
We're getting a crash in certain regions when querying `aws_vpc_eip` and including the `arn` column. The error is:

```
Error: rpc error: code = Internal desc = hydrate function getVpcEipARN failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
```

**Steampipe version (`steampipe -v`)**
v0.16.1

**Plugin version (`steampipe plugin list`)**
aws@latest 0.76.0

**To reproduce**
```
steampipe query "select arn from <profile>.aws_vpc_eip"

Error: rpc error: code = Internal desc = hydrate function getVpcEipARN failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
```

**Expected behavior**
No crash, the arn and allocation_id fields should be null.

**Additional context**
Using the aws cli, I noticed that this region has an EIP that doesn't have an allocation ID, etc.. Other EIPs in this region, and all EIPs in other regions that don't crash have allocation IDs and some other fields.

```
aws --profile <profile> --region us-east-1 ec2 describe-addresses
{
  "Addresses": [
    {
      "InstanceId": "",
      "PublicIp": "x.x.x.x",
      "Domain": "standard",
      "PublicIpv4Pool": "amazon"
    },
   ...
  ]
}
```

**Comment by cbruno10** [comment]
Hey @ben417 , sorry you ran into this issue!

It does seem odd that the EIP doesn't have an allocation ID. Do you know is this EIP in a VPC, or is it perhaps an older one created in [EC2-Classic](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-classic-platform.html)? From the [response examples](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAddresses.html#API_DescribeAddresses_Examples), it looks the allocation ID isn't returned when the EIP was not created in a VPC.

**Comment by ben417** [comment]
Yes, I checked in the console and it says EC2-Classic.

**Comment by cbruno10** [comment]
@ben417 Whoa, first time I've seen an account still on EC2-Classic I think 😄 

Let me take a look at how we can handle any columns in the `aws_vpc_eip` table that may be affected by the lack of properties in EC2-Classic compared to EC2-VPC.

Do you have any other resources still in EC2-Classic? If so, I'd be curious to know if queries like `select * from ...` all succeed, or do you run into any errors with those as well? Thanks!

**Comment by ben417** [comment]
I went through all the aws_* tables and didn't really see any errors that looked like the one above.

This is the only other error that stood out, but I don't think it's related to EC2 classic. All route tables are in VPCs.

```
> select * from <profile>.aws_vpc_route where region = 'us-west-2'
Error: interface conversion: interface {} is types.RouteTable, not *ec2.RouteTable (SQLSTATE HV000)

> select route_table_id,vpc_id from <profile>.aws_vpc_route_table where region = 'us-west-2'
+----------------+--------------+
| route_table_id | vpc_id       |
+----------------+--------------+
| rtb-xxxxxxxx   | vpc-xxxxxxxx |
| rtb-xxxxxxxx   | vpc-xxxxxxxx |
| rtb-xxxxxxxx   | vpc-xxxxxxxx |
+----------------+--------------+
```

**Comment by cbruno10** [comment]
@ben417 Thank you for testing the other resource types!

For the `aws_vpc_route` table issue, I just pushed a commit (https://github.com/turbot/steampipe-plugin-aws/commit/b70457ecb063260998bf2da222e1188680c5c3d7) to address this. This fix will be released later this week, but if you'd like to try it earlier, you can make run `make` in a cloned copy of this repo locally and then your queries against `aws_vpc_route` should work. 

For the VPC EIP errors, I pushed a fix to the `fix-vpc-eip-ec2-classic` branch, but I couldn't test my fixes since I can't create any EIPs in EC2-Classic.

If you have time, can you please pull that branch down locally, run `make`, and then see if `select * from aws_vpc_eip` produces the results you expect? Now, `arn` will always be `null` (since EIP ARNs need an allocation ID), while the title falls back to the value in `public_ip` (not great, but not much else to work with unfortunately in the response data).

**Comment by ben417** [comment]
@cbruno10 Thanks and np. It still fails for me with the same error message.

**Comment by cbruno10** [comment]
@ben417 I've just pushed an update to the `fix-vpc-eip-ec2-classic` branch that adds more logging statements.

Can you please pull the latest commits, re-run `Make`, and then run `select arn from <profile>.aws_vpc_eip`? Afterward, can you please check your plugin logs in `~/.steampipe/logs/plugin-<current date>.log`, and paste any log statements containing `aws_vpc_eip.getVpcEipARN` here (removing any sensitive info, like account IDs or IPs)?

Also, thanks for helping with the multiple tests! Unfortunately, I'm having a bit of difficult reproducing from my end since all of my EIPs are in a VPC.

**Comment by ben417** [comment]
@cbruno10 Thanks, I pulled the commits and reran make. Here's the log file.
[plugin-2022-09-15.log](https://github.com/turbot/steampipe-plugin-aws/files/9576374/plugin-2022-09-15.log)

**Comment by cbruno10** [comment]
Thanks @ben417 , those log messages were very helpful.

I've just pushed a final fix (hopefully) into the `fix-vpc-eip-ec2-classic` branch. Can you please retry your queries and see if they produce any unexpected errors?

Also, please note that the `arn` and `akas` columns for EIPs in EC2-Classic are expected to be `<null>` and the `title` column is the value of `public_ip`.

**Comment by ben417** [comment]
@cbruno10, Yes, the query completes now with no errors and the fields are null as expected. 

Thanks for your help!
